# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 624b9d6a10b06367097d9c44a2f985bca3e31d0ca64cfaa24caad2711af8ad5b77a6db8a34256c0081d63ea846a133f206d63ed34713fa8aad3fa6fa8301a9b6

test:
  secret_key_base: 03f9de7397e934be49e64b881cfcf2cfc478dbbfa6e14dd3396bdaacd6f5d2fa4e33dbd601e2ef7e09f5b0d0888bc3d8647c5b8355d53afd1f51bc02317a02ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
